In [20]:
#Import pandas and numpy to handle and oraganize the data
import pandas as pd
import numpy as np

'''
imports from the scikit library what we need.  The first item is our Kfold module.
Note also that we could have imported both kFold, train_test_split and cross_val_score all on the same line as 
"from sklearn.model_selection" using commas to seperate.  The point is just to clearly indicate the different modules
we will be using, seperatly.  
'''

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

#Import the LinearRegression module to run our model
from sklearn.linear_model import LinearRegression


In [12]:
#Import our example data directly from the URL:
data_set = 'http://www-bcf.usc.edu/~gareth/ISL/Auto.csv'

In [13]:
#read the data in to a pandas dataframe
data = pd.read_csv(data_set, sep=',')

In [17]:
#take a look at the first few lines of data to check that we imported correctly
data.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [21]:
#for this excercise we will try to predict mpg based upon 'cylinders' and 'weight' alone.  

In [ ]:
# X will be our independent variables and y is our dependent variable we want to predict:

In [24]:
X = data[['cylinders','weight']]
y = data['mpg']

In [26]:
#split our data into a training set and a test set using the train_test_split module:
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [ ]:
#Now we get to the KFold part, where we will evaluate scores based on different sets of data from the Train set.

In [31]:
#Finally we get to our KFold module:
kf = KFold(n_splits=5,shuffle=True, random_state=123)
#for our kf we said we want to split the data into 5 sets and run the text 5 times, Shuffle=True
#will create our kfold sets randomly so that we don't introduce some bias into the data by taking the data points
#in some order.  Lastly, we set a 'random_state' known most other places as a random seed so that we can reproduce
#our random splits later if we choose too.

In [32]:
#First we instantiate our model. In this case it is a Linear regression model:
lr = LinearRegression()

In [34]:
#now we evaluate our model using the number of k-folds. Note that the 'cv' term is equal to our kf module we set above
cv_scores = cross_val_score(lr,X_train,y_train,cv=kf)
cv_scores

array([0.67148329, 0.64933883, 0.67198445, 0.71496077, 0.75616795])

In [35]:
'''
Now we can see our scores above.  Each k-fold times, we run the model, produce the score, discard that model, run a new model
and rescore.  We repeat that for, in this case, 5 times.  Below we will try splitting the data 10 times:
'''

kf = KFold(n_splits=10,shuffle=True, random_state=123)
cv_scores = cross_val_score(lr,X_train,y_train,cv=kf)
cv_scores

array([0.6085157 , 0.74126423, 0.78810916, 0.44964697, 0.61031181,
       0.71933964, 0.72388894, 0.70747354, 0.70051973, 0.81185266])

In [37]:
'''
Now we can see our scores above.  Each k-fold times, we run the model, produce the score, discard that model, run a new model
and rescore.  We repeat that for, in this case, 5 times.  Below we will try splitting the data 10 times:
'''

kf = KFold(n_splits=10,shuffle=True, random_state=123)
cv_scores = cross_val_score(lr,X_train,y_train,cv=kf)
cv_scores

array([0.6085157 , 0.74126423, 0.78810916, 0.44964697, 0.61031181,
       0.71933964, 0.72388894, 0.70747354, 0.70051973, 0.81185266])

In [36]:
'''
now we see that we get 10 scores. In this case, our scores are the R-Squared score.  The variation we see in the scores
is due to how we split our data up.  Also, we have a smaller data set which may increase the variability we see in our
cross val scores
'''

#finally, we can average all the scores from all the cross validations and get an average score for our model:
cv_scores.mean()

0.6860922377219947